In [1]:
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as snsx
import dtale
import ydata_profiling 
import klib
from pandas_profiling import ProfileReport
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import joblib
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import GridSearchCV
from xgboost import XGBRegressor
from sklearn.ensemble import GradientBoostingRegressor

C:\Users\Softlaptop\AppData\Local\Temp\ipykernel_13000\2856112043.py:9: DeprecationWarning:

`import pandas_profiling` is going to be deprecated by April 1st. Please use `import ydata_profiling` instead.

In [2]:
df_train = pd.read_csv('D:/Users/ao920/Desktop/New folder/Train.csv')
df_test = pd.read_csv('D:/Users/ao920/Desktop/New folder/Test.csv')
df_train.head()
df_test.head()
#df_train.describe()
#df_test.describe()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type
0,FDW58,20.750,Low Fat,0.007565,Snack Foods,107.8622,OUT049,1999,Medium,Tier 1,Supermarket Type1
1,FDW14,8.300,reg,0.038428,Dairy,87.3198,OUT017,2007,NaN,Tier 2,Supermarket Type1
2,NCN55,14.600,Low Fat,0.099575,Others,241.7538,OUT010,1998,NaN,Tier 3,Grocery Store
3,FDQ58,7.315,Low Fat,0.015388,Snack Foods,155.0340,OUT017,2007,NaN,Tier 2,Supermarket Type1
4,FDY38,NaN,Regular,0.118599,Dairy,234.2300,OUT027,1985,Medium,Tier 3,Supermarket Type3

In [5]:
df_train['Item_Weight'].fillna(df_train['Item_Weight'].mean(),inplace=True)
df_test['Item_Weight'].fillna(df_test['Item_Weight'].mean(),inplace=True)
df_train['Outlet_Size'].fillna(df_train['Outlet_Size'].mode()[0],inplace=True)
df_test['Outlet_Size'].fillna(df_test['Outlet_Size'].mode()[0],inplace=True)
df_train.drop(['Item_Identifier','Outlet_Identifier'],axis=1,inplace=True)
df_test.drop(['Item_Identifier','Outlet_Identifier'],axis=1,inplace=True)
df_train.head()

KeyError: "['Item_Identifier', 'Outlet_Identifier'] not found in axis"

In [61]:
profile = ProfileReport(df_train, title="Report")
profile

In [63]:
#Exploratory Data Analysis (eda) - Outliers
# Calculate the z-scores 
z_scores = (df_train.select_dtypes(include=np.number) - df_train.select_dtypes(include=np.number).mean()) / df_train.select_dtypes(include=np.number).std()

outliers = (z_scores.abs() > 3).any(axis=1)

# Print outliers found
print("Number of outliers in the train dataset:", outliers.sum())

# Calculate the z-scores 
z_scores_test = (df_test.select_dtypes(include=np.number) - df_test.select_dtypes(include=np.number).mean()) / df_test.select_dtypes(include=np.number).std()

outliers_test = (z_scores_test.abs() > 3).any(axis=1)

# Print outliers found
print("Number of outliers in the test dataset:", outliers_test.sum())

Number of outliers in the train dataset: 185
Number of outliers in the test dataset: 81

In [64]:
 #Remove outliers from the train dataset
train_data_no_outliers = df_train[~outliers]

# Remove outliers from the test dataset
test_data_no_outliers = df_test[~outliers_test]

In [73]:
# Exploratory Data Analysis (eda) - Graphs
# Visualize numerical columns
numerical_columns = df_train.select_dtypes(include=[np.number]).columns
fig, axes = plt.subplots(nrows=len(numerical_columns), ncols=1, figsize=(8, 6 * len(numerical_columns)))
for i, column in enumerate(numerical_columns):
    ax = axes[i]
    sns.histplot(df_train[column], ax=ax, bins=20)
    ax.set_xlabel(column)
plt.tight_layout()
plt.show()

In [ ]:
klib.data_cleaning(df_train) # performs datacleaning (drop duplicates & empty rows/cols, adjust dtypes)
klib.clean_column_names(df_train) # cleans and standardizes column names, also called inside data_cleaning()

In [78]:

#Converting Categorical To Numerical
le=LabelEncoder()
df_train['item_fat_content']= le.fit_transform(df_train['item_fat_content'])
df_train['item_type']= le.fit_transform(df_train['item_type'])
df_train['outlet_size']= le.fit_transform(df_train['outlet_size'])
df_train['outlet_location_type']= le.fit_transform(df_train['outlet_location_type'])
df_train['outlet_type']= le.fit_transform(df_train['outlet_type'])
df_train

,item_weight,item_fat_content,item_visibility,item_type,item_mrp,outlet_establishment_year,outlet_size,outlet_location_type,outlet_type,item_outlet_sales
0,9.300,1,0.016047,4,249.8092,1999,1,0,1,3735.1380
1,5.920,2,0.019278,14,48.2692,2009,1,2,2,443.4228
2,17.500,1,0.016760,10,141.6180,1999,1,0,1,2097.2700
3,19.200,2,0.000000,6,182.0950,1998,1,2,0,732.3800
4,8.930,1,0.000000,9,53.8614,1987,0,2,1,994.7052
...,...,...,...,...,...,...,...,...,...,...
8518,6.865,1,0.056783,13,214.5218,1987,0,2,1,2778.3834
8519,8.380,2,0.046982,0,108.1570,2002,1,1,1,549.2850
8520,10.600,1,0.035186,8,85.1224,2004,2,1,1,1193.1136
8521,7.210,2,0.145221,13,103.1332,2009,1,2,2,1845.5976
8522,14.800,1,0.044878,14,75.4670,1997,2,0,1,765.6700

In [79]:
X=df_train.drop('item_outlet_sales',axis=1)
Y=df_train['item_outlet_sales']

In [84]:
#Seperating Training And Test Data
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, random_state=101, test_size=0.2)
X.describe()

In [86]:
# step 9  Standard Scaling 06m Robust Scaling
sc= StandardScaler()
X_train_std= sc.fit_transform(X_train)
X_test_std= sc.transform(X_test)
X_train_std
X_test_std
Y_train
Y_test

8179     904.8222
8355    2795.6942
3411    1947.4650
7089     872.8638
6954    2450.1440
          ...
1317    1721.0930
4996     914.8092
531      370.1848
3891    1358.2320
6629    2418.1856
Name: item_outlet_sales, Length: 1705, dtype: float64

In [88]:
lr= LinearRegression()
lr.fit(X_train_std,Y_train)
X_test.head()
Y_pred_lr=lr.predict(X_test_std)

In [94]:
print(r2_score(Y_test,Y_pred_lr))
print(mean_absolute_error(Y_test,Y_pred_lr))
print(np.sqrt(mean_squared_error(Y_test,Y_pred_lr)))
# RandomForestRegressor
rf= RandomForestRegressor(n_estimators=1000)
rf.fit(X_train_std,Y_train)
Y_pred_rf= rf.predict(X_test_std)
print(r2_score(Y_test,Y_pred_rf))
print(mean_absolute_error(Y_test,Y_pred_rf))
print(np.sqrt(mean_squared_error(Y_test,Y_pred_rf)))

0.5480041092435074
783.3274514058648
1109.8890319104137

In [ ]:
# Step 10 (XGB and GBR)
x

# hyperparameter grids for XGBoost
xgb_param_grid = {
    'n_estimators': [100, 200, 500],
    'learning_rate': [0.01, 0.1, 0.2],
    'max_depth': [3, 5, 7]
}

#  grid search cross-validation
xgb_grid_search = GridSearchCV(estimator=XGBRegressor(random_state=42), param_grid=xgb_param_grid, cv=5)
xgb_grid_search.fit(X_train_std, Y_train)

#  XGBoost model and its hyperparameters
best_xgb_model = xgb_grid_search.best_estimator_

#  hyperparameter grids for Gradient Boosting
gbr_param_grid = {
    'n_estimators': [100, 200, 500],
    'learning_rate': [0.01, 0.1, 0.2],
    'max_depth': [3, 5, 7]
}

#  grid search cross-validation for Gradient Boosting
gbr_grid_search = GridSearchCV(estimator=GradientBoostingRegressor(random_state=42), param_grid=gbr_param_grid, cv=5)
gbr_grid_search.fit(X_train_std, Y_train)

# Gradient Boosting model and its hyperparameters
best_gbr_model = gbr_grid_search.best_estimator_

# Step 11: Final Predictions on the Test Dataset
Y_pred_xgb = best_xgb_model.predict(X_test_std)
Y_pred_gbr = best_gbr_model.predict(X_test_std)

# Step 12: Saving the Final Model
joblib.dump(best_xgb_model, 'xgb_model.pkl')
joblib.dump(best_gbr_model, 'gbr_model.pkl')

2023-07-06 18:41:37,155 - INFO     - Executing shutdown due to inactivity...
2023-07-06 18:41:41,798 - INFO     - Executing shutdown...
2023-07-06 18:41:41,807 - ERROR    - Exception on /shutdown [GET]
Traceback (most recent call last):
  File "c:\Users\Softlaptop\anaconda3\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\Users\Softlaptop\anaconda3\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\Users\Softlaptop\anaconda3\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\Softlaptop\anaconda3\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "c:\Users\Softlaptop\anaconda3\lib\site-packages\dtale\app.py", line 440, in shutdown
    shutdown_server()
  File "c:\Users\Softlaptop\anaconda3\lib\site-packages\dtale\app.py", line 426, in shutdown_server
    raise RuntimeError("Not running with the Werkzeug Server")
RuntimeError: Not running with the Werkzeug Server

:

: